config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'
  resources :blogs, only: [:index,:show]

  resources :articles, only: [:index,:show]

  namespace :api do
    namespace :v1 do
      resources :blogs, only: [:index,:show]
      resources :articles, only: [:index,:show]
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :blog

  scope :title_has, ->(key) {where("title LIKE ?","%#{key}%")}
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :articles
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < Api::V1::BaseController
  def index
    if params[:search]
      @articles=Article.title_has(params[:search]).order(views: :desc,published: :desc)
    else
      @articles=Article.order(views: :desc,published: :desc)
    end
    render(json: @articles, each_serializer: Api::V1::ArticlesSerializer)
  end

  def show
    @article=Article.find(params[:id])
    render(json: @article,serializer: Api::V1::ArticlesSerializer)
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  protect_from_forgery with: :null_session

    before_action :destroy_session

    def destroy_session
      request.session_options[:skip] = true
    end
end

app/controllers/api/v1/blogs_controller.rb
class Api::V1::BlogsController < Api::V1::BaseController
  def index
    @blogs=Blog.all
    render(json: @blogs, each_serializer: Api::V1::BlogsSerializer)
  end

  def show
    @blog=Blog.find(params[:id])
    @articles=@blog.articles.order(views: :desc,published: :desc)
    render(json: @blog,serializer: Api::V1::SingleBlogsSerializer, root: "blog" )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    if Rails.env.production?
    if params[:search]
      @articles=Article.title_has(params[:search]).order("updated_at DESC","views DESC","published DESC NULLS LAST").page(params[:page])
    else
      @articles=Article.order("updated_at DESC","views DESC","published DESC NULLS LAST").page(params[:page])
    end
  else
    if params[:search]
      @articles=Article.title_has(params[:search]).order("updated_at DESC","views DESC","published DESC").page(params[:page])
    else
      @articles=Article.order("updated_at DESC","views DESC","published DESC").page(params[:page])
    end
  end
  end

  def show
    @article=Article.find(params[:id])
    @article.views=@article.views+1
    @article.save
    redirect_to @article.url
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs=Blog.all.page(params[:page])
  end

  def show
    @blog=Blog.find(params[:id])
    @articles=@blog.articles.order(views: :desc,published: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <div class="article">
  <%= link_to article.title, article, data: {no_turbolink: true} %> <span class="site">from <%= link_to article.blog.name,article.blog.url, data: {no_turbolink: true} %> </span>
  <div class="subtext"> Published <%= time_ago_in_words(article.published) unless article.published.blank? %> ago | <%= article.views %> views </div>
</div>
<% end %>
<%= will_paginate @articles %>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>

app/views/blogs/index.html.erb
<% @blogs.each do |blog| %>
    <div class="blog">
      <div class="name">
    <%= link_to blog.name, blog %>
  </div>
    <div class="url"><%= link_to blog.url, blog.url, data: {no_turbolink: true} %></div>
  </div>
<% end %>
<%= will_paginate @blogs %>

app/views/blogs/show.html.erb
<h1><%= @blog.name %> </h1>
<% @articles.each do |article| %>
  <div class="article">
  <div class="title"><%= link_to article.title,article %> </div>
  <div class="subtext"> Published : <%= time_ago_in_words(article.published) unless article.published.blank? %> ago | <%= article.views %> views
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackersblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="nav navbar-header">
      <%= link_to "HackerBlogs", root_path, class: "navbar navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Tracked Blogs", blogs_path %></li>
    </ul>

    <div class="col-sm-3 col-md-3 pull-right">
      <%= form_tag root_path,method: "get",class: "navbar-form" do %>
      <div class="input-group">
        <%= text_field_tag :search,params[:search],class: "form-control", placeholder: "Search articles" %>
        <div class="input-group-btn">
        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
      </div>
      </div>
      <% end %>
    </div>
  </nav>

<%= yield %>

</body>
</html>